# Generated by Django 3.0.8 on 2020-07-14 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_likedby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='data',
        ),
        migrations.CreateModel(
            name='blog_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HEADING', 'HEADING'), ('SUBHEADING', 'SUBHEADING'), ('IMAGE', 'IMAGE'), ('PARAGRAPH', 'PARAGRAPH')], max_length=30)),
                ('context', models.TextField()),
                ('position', models.IntegerField()),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
            ],
            options={
                'unique_together': {('blog', 'position')},
            },
        ),
    ]
