# Generated by Django 3.0.8 on 2020-07-14 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200714_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogdata',
            old_name='context',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_data', to='blog.Blog'),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='position',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
