# Generated by Django 3.0.8 on 2020-07-17 04:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200714_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedby',
            name='liked_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
